services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: <host>
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: <db_name>
      - key: DB_USERNAME
        value: <db_user>
      - key: DB_PASSWORD
        value: <db_pass>
