server {
    listen 80;
    index index.php index.html;
    root /var/www/html/public;  # A raiz do seu aplicativo Laravel (onde o Vite gera os assets)

    location / {
        try_files $uri $uri/ /index.php?$query_string;  # Redireciona para index.php para Laravel
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;  # PHP-FPM escuta nessa porta
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Acesso aos arquivos estáticos do Vue.js (compilados)
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|woff|woff2|eot|ttf|otf|ico)$ {
        root /var/www/html/public;  # A pasta pública onde o Vite coloca os arquivos compilados
        try_files $uri /index.php?$query_string;
    }

    location ~ /\.ht {
        deny all;
    }
}
